use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Agent label used for Claude Code sessions, matching `agent_resume` and detection.
pub const CLAUDE_AGENT: &str = "claude";

/// Where a session's title came from, in priority order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum TitleKind {
    /// Set explicitly by the user (`/rename` in Claude Code).
    Custom,
    /// Generated by the agent.
    Ai,
    /// Conversation summary written by older agent builds.
    Summary,
    /// No title recorded; callers fall back to the first prompt.
    None,
}

/// Metadata for one past agent session, derived from its transcript file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionRecord {
    pub agent: String,
    pub session_id: String,
    /// Working directory the session ran in.
    pub project_path: String,
    /// Main checkout when the session ran inside a git worktree.
    #[serde(default)]
    pub original_cwd: Option<String>,
    #[serde(default)]
    pub git_branch: String,
    #[serde(default)]
    pub title: Option<String>,
    pub title_kind: TitleKind,
    #[serde(default)]
    pub first_prompt: String,
    pub first_ts_ms: i64,
    pub last_ts_ms: i64,
    /// User and assistant messages, excluding sidechains.
    pub message_count: u32,
    pub transcript_path: PathBuf,
    pub file_len: u64,
    pub file_mtime_ms: i64,
    /// Bytes of cached body text; zero when nothing was cached.
    #[serde(default)]
    pub text_len: u64,
}

impl SessionRecord {
    /// Title, else first prompt, else the session id.
    pub fn display_title(&self) -> &str {
        match self.title.as_deref() {
            Some(title) if !title.is_empty() => title,
            _ if !self.first_prompt.is_empty() => &self.first_prompt,
            _ => &self.session_id,
        }
    }

    /// Directory a resumed session should open in: the main checkout for worktree
    /// sessions, otherwise the recorded working directory.
    pub fn workspace_path(&self) -> &str {
        self.original_cwd
            .as_deref()
            .filter(|cwd| !cwd.is_empty())
            .unwrap_or(&self.project_path)
    }
}

/// Short label for a project path: its last non-empty component.
pub fn project_label(path: &str) -> String {
    let trimmed = path.trim_end_matches(['/', '\\']);
    let label = trimmed
        .rsplit(['/', '\\'])
        .find(|part| !part.is_empty())
        .unwrap_or(trimmed);
    if label.is_empty() {
        path.to_string()
    } else {
        label.to_string()
    }
}

/// Best-effort decode of a Claude Code project directory name such as
/// `-Users-me-src-app` into `/Users/me/src/app`. Lossy for paths containing `-`;
/// only used when the transcript itself records no working directory.
pub fn project_path_from_dir_name(name: &str) -> Option<String> {
    let rest = name.strip_prefix('-')?;
    if rest.is_empty() {
        return None;
    }
    Some(format!("/{}", rest.replace('-', "/")))
}

/// Returns the session id when `name` is `<uuid>.jsonl`.
pub fn is_session_file_name(name: &str) -> Option<&str> {
    let stem = name.strip_suffix(".jsonl")?;
    looks_like_uuid(stem).then_some(stem)
}

fn looks_like_uuid(value: &str) -> bool {
    let bytes = value.as_bytes();
    if bytes.len() != 36 {
        return false;
    }
    bytes.iter().enumerate().all(|(index, byte)| match index {
        8 | 13 | 18 | 23 => *byte == b'-',
        _ => byte.is_ascii_hexdigit(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn project_label_uses_last_component() {
        assert_eq!(project_label("/Users/me/src/app"), "app");
        assert_eq!(project_label("/Users/me/src/app/"), "app");
        assert_eq!(project_label("C:\\work\\thing"), "thing");
        assert_eq!(project_label("/"), "/");
        assert_eq!(project_label(""), "");
    }

    #[test]
    fn decodes_claude_project_dir_names() {
        assert_eq!(
            project_path_from_dir_name("-Users-me-src-app").as_deref(),
            Some("/Users/me/src/app")
        );
        assert_eq!(project_path_from_dir_name("-"), None);
        assert_eq!(project_path_from_dir_name("plain"), None);
    }

    #[test]
    fn recognises_session_file_names() {
        assert_eq!(
            is_session_file_name("8001ceb0-f5cc-4b99-8451-2bce8b04d117.jsonl"),
            Some("8001ceb0-f5cc-4b99-8451-2bce8b04d117")
        );
        assert_eq!(is_session_file_name("agent-abc123.jsonl"), None);
        assert_eq!(is_session_file_name("sessions-index.json"), None);
        assert_eq!(
            is_session_file_name("8001ceb0-f5cc-4b99-8451-2bce8b04d117.json"),
            None
        );
    }

    #[test]
    fn display_title_falls_back_in_order() {
        let mut record = sample();
        assert_eq!(record.display_title(), "Renamed");
        record.title = None;
        assert_eq!(record.display_title(), "first prompt");
        record.first_prompt.clear();
        assert_eq!(record.display_title(), "id-1");
    }

    #[test]
    fn workspace_path_prefers_original_checkout() {
        let mut record = sample();
        assert_eq!(record.workspace_path(), "/proj");
        record.original_cwd = Some("/main".into());
        assert_eq!(record.workspace_path(), "/main");
        record.original_cwd = Some(String::new());
        assert_eq!(record.workspace_path(), "/proj");
    }

    fn sample() -> SessionRecord {
        SessionRecord {
            agent: CLAUDE_AGENT.into(),
            session_id: "id-1".into(),
            project_path: "/proj".into(),
            original_cwd: None,
            git_branch: String::new(),
            title: Some("Renamed".into()),
            title_kind: TitleKind::Custom,
            first_prompt: "first prompt".into(),
            first_ts_ms: 0,
            last_ts_ms: 0,
            message_count: 0,
            transcript_path: PathBuf::from("/x.jsonl"),
            file_len: 0,
            file_mtime_ms: 0,
            text_len: 0,
        }
    }
}
